function Code_FigPopdyn(X1, YMatrix1, X2, YMatrix2, X3, YMatrix3, X4, YMatrix4, X5, YMatrix5, X6, YMatrix6, X7, YMatrix7, X8, YMatrix8, X9, YMatrix9, X10, YMatrix10, X11, YMatrix11, X12, YMatrix12, X13, YMatrix13)
%CREATEFIGURE(X1, YMATRIX1, X2, YMATRIX2, X3, YMATRIX3, X4, YMATRIX4, X5, YMATRIX5, X6, YMATRIX6, X7, YMATRIX7, X8, YMATRIX8, X9, YMATRIX9, X10, YMATRIX10, X11, YMATRIX11, X12, YMATRIX12, X13, YMATRIX13)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  X2:  vector of x data
%  YMATRIX2:  matrix of y data
%  X3:  vector of x data
%  YMATRIX3:  matrix of y data
%  X4:  vector of x data
%  YMATRIX4:  matrix of y data
%  X5:  vector of x data
%  YMATRIX5:  matrix of y data
%  X6:  vector of x data
%  YMATRIX6:  matrix of y data
%  X7:  vector of x data
%  YMATRIX7:  matrix of y data
%  X8:  vector of x data
%  YMATRIX8:  matrix of y data
%  X9:  vector of x data
%  YMATRIX9:  matrix of y data
%  X10:  vector of x data
%  YMATRIX10:  matrix of y data
%  X11:  vector of x data
%  YMATRIX11:  matrix of y data
%  X12:  vector of x data
%  YMATRIX12:  matrix of y data
%  X13:  vector of x data
%  YMATRIX13:  matrix of y data

%  Auto-generated by MATLAB on 22-Dec-2017 03:25:28

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.0485678704856787 0.0801630434782609 0.93867552092026 0.915749763061249]);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'LineWidth',2,'Color',[0 0 0]);
set(plot1(1),'DisplayName','Lysogens');
set(plot1(2),'DisplayName','CRISPR Bacteria','LineStyle','-.');
set(plot1(3),'DisplayName','Bacteriophage','LineStyle','--');

% Create xlabel
xlabel('Time t (hrs)','FontSize',17.6);

% Create ylabel
ylabel('Population Densities (cells/cm^2)','FontSize',17.6);

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',16,'LineStyleOrderIndex',3,'XTick',zeros(1,0),...
    'XTickLabel',{},'YTick',zeros(1,0),'YTickLabel',{''});
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.287136180419892 0.0117481403898769 0.50524246395806 0.0300957592339261],...
    'Orientation','horizontal',...
    'FontSize',14.4);

% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.109917987542271 0.804240022601558 0.232679906305577 0.157318741450068]);
hold(axes2,'on');

% Create multiple lines using matrix input to semilogy
semilogy1 = semilogy(X1,YMatrix1,'Parent',axes2,'LineWidth',2,...
    'Color',[0 0 0]);
set(semilogy1(1),'DisplayName','Lysogens');
set(semilogy1(2),'DisplayName','CRISPR Bacteria','LineStyle','-.');
set(semilogy1(3),'DisplayName','Bacteriophage','LineStyle','--');

% Create multiple lines using matrix input to semilogy
semilogy2 = semilogy(X2,YMatrix2,'Parent',axes2,'LineWidth',2);
set(semilogy2(1),'DisplayName','L_{000}','Color',[0.5 0.5 0.5]);
set(semilogy2(2),'DisplayName','L_{001}','Color',[0 0 1]);
set(semilogy2(3),'DisplayName','L_{010}',...
    'Color',[0 1 0]);
set(semilogy2(4),'DisplayName','L_{011}','Color',[0 1 1]);
set(semilogy2(5),'DisplayName','L_{100}',...
    'Color',[1 0 0]);
set(semilogy2(6),'DisplayName','L_{101}',...
    'Color',[1 0 1]);
set(semilogy2(7),'DisplayName','L_{110}',...
    'Color',[1 0.5 0.5]);
set(semilogy2(8),'DisplayName','L_{111}','Color',[0 0 0]);
set(semilogy2(9),'DisplayName','C_{000}','LineStyle','-.','Color',[0.5 0.5 0.5]);
set(semilogy2(10),'DisplayName','C_{001}','LineStyle','-.','Color',[0 0 1]);
set(semilogy2(11),'DisplayName','C_{010}','LineStyle','-.',...
    'Color',[0 1 0]);
set(semilogy2(12),'DisplayName','C_{011}','LineStyle','-.','Color',[0 1 1]);
set(semilogy2(13),'DisplayName','C_{100}','LineStyle','-.',...
    'Color',[1 0 0]);
set(semilogy2(14),'DisplayName','C_{101}','LineStyle','-.',...
    'Color',[1 0 1]);
set(semilogy2(15),'DisplayName','C_{110}','LineStyle','-.',...
    'Color',[1 0.5 0.5]);
set(semilogy2(16),'DisplayName','C_{111}','LineStyle','-.','Color',[0 0 0]);
set(semilogy2(17),'LineWidth',2,'LineStyle','--','Color',[0 0 1]);
set(semilogy2(18),'LineWidth',2,'LineStyle','--','Color',[0 1 1]);
set(semilogy2(19),'LineWidth',3,'LineStyle','--','Color',[0 0 0]);

% Create title
title('\{1,2\}','FontSize',17.6);

% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes2,[1e-07 1000000000]);
box(axes2,'on');
% Set the remaining axes properties
set(axes2,'FontSize',16,'LineStyleOrderIndex',3,'XMinorTick','on',...
    'YMinorTick','on','YScale','log','YTick',[1e-05 1 100000],'YTickLabel',...
    {'10^{-5}','10^{0}','10^{5}'});
% Create axes
axes3 = axes('Parent',figure1,...
    'Position',[0.413785051349908 0.801504044489382 0.239831697054698 0.159474829861738]);
hold(axes3,'on');

% Create multiple lines using matrix input to semilogy
semilogy3 = semilogy(X1,YMatrix1,'Parent',axes3,'LineWidth',2,...
    'Color',[0 0 0]);
set(semilogy3(1),'DisplayName','Lysogens');
set(semilogy3(2),'DisplayName','CRISPR Bacteria','LineStyle','-.');
set(semilogy3(3),'DisplayName','Bacteriophage','LineStyle','--');

% Create multiple lines using matrix input to semilogy
semilogy4 = semilogy(X3,YMatrix3,'Parent',axes3,'LineWidth',2);
set(semilogy4(1),'DisplayName','L_{000}','Color',[0.5 0.5 0.5]);
set(semilogy4(2),'DisplayName','L_{001}','Color',[0 0 1]);
set(semilogy4(3),'DisplayName','L_{010}',...
    'Color',[0 1 0]);
set(semilogy4(4),'DisplayName','L_{011}','Color',[0 1 1]);
set(semilogy4(5),'DisplayName','L_{100}',...
    'Color',[1 0 0]);
set(semilogy4(6),'DisplayName','L_{101}',...
    'Color',[1 0 1]);
set(semilogy4(7),'DisplayName','L_{110}',...
    'Color',[1 0.5 0.5]);
set(semilogy4(8),'DisplayName','L_{111}','Color',[0 0 0]);
set(semilogy4(9),'DisplayName','C_{000}','LineStyle','-.','Color',[0.5 0.5 0.5]);
set(semilogy4(10),'DisplayName','C_{001}','LineStyle','-.','Color',[0 0 1]);
set(semilogy4(11),'DisplayName','C_{010}','LineStyle','-.',...
    'Color',[0 1 0]);
set(semilogy4(12),'DisplayName','C_{011}','LineStyle','-.','Color',[0 1 1]);
set(semilogy4(13),'DisplayName','C_{100}','LineStyle','-.',...
    'Color',[1 0 0]);
set(semilogy4(14),'DisplayName','C_{101}','LineStyle','-.',...
    'Color',[1 0 1]);
set(semilogy4(15),'DisplayName','C_{110}','LineStyle','-.',...
    'Color',[1 0.5 0.5]);
set(semilogy4(16),'DisplayName','C_{111}','LineStyle','-.','Color',[0 0 0]);
set(semilogy4(17),'LineWidth',2,'LineStyle','--','Color',[0 0 1]);
set(semilogy4(18),'LineWidth',2,'LineStyle','--','Color',[0 1 1]);
set(semilogy4(19),'LineWidth',3,'LineStyle','--','Color',[0 0 0]);

% Create title
title('\{1,2\}','FontSize',17.6);

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes3,[0 180]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes3,[1e-07 1000000000]);
box(axes3,'on');
% Set the remaining axes properties
set(axes3,'FontSize',16,'LineStyleOrderIndex',3,'XMinorTick','on',...
    'YMinorTick','on','YScale','log','YTick',[1e-05 1 100000],'YTickLabel',...
    {'10^{-5}','10^{0}','10^{5}'});
% Create axes
axes4 = axes('Parent',figure1,...
    'Position',[0.725750971449385 0.801504044489382 0.232819074333801 0.159579366046682]);
hold(axes4,'on');

% Create multiple lines using matrix input to semilogy
semilogy5 = semilogy(X1,YMatrix1,'Parent',axes4,'LineWidth',2,...
    'Color',[0 0 0]);
set(semilogy5(1),'DisplayName','Lysogens');
set(semilogy5(2),'DisplayName','CRISPR Bacteria','LineStyle','-.');
set(semilogy5(3),'DisplayName','Bacteriophage','LineStyle','--');

% Create multiple lines using matrix input to semilogy
semilogy6 = semilogy(X4,YMatrix4,'Parent',axes4,'LineWidth',2);
set(semilogy6(1),'DisplayName','L_{000}','Color',[0.5 0.5 0.5]);
set(semilogy6(2),'DisplayName','L_{001}','Color',[0 0 1]);
set(semilogy6(3),'DisplayName','L_{010}',...
    'Color',[0 1 0]);
set(semilogy6(4),'DisplayName','L_{011}','Color',[0 1 1]);
set(semilogy6(5),'DisplayName','L_{100}',...
    'Color',[1 0 0]);
set(semilogy6(6),'DisplayName','L_{101}',...
    'Color',[1 0 1]);
set(semilogy6(7),'DisplayName','L_{110}',...
    'Color',[1 0.5 0.5]);
set(semilogy6(8),'DisplayName','L_{111}','Color',[0 0 0]);
set(semilogy6(9),'DisplayName','C_{000}','LineStyle','-.','Color',[0.5 0.5 0.5]);
set(semilogy6(10),'DisplayName','C_{001}','LineStyle','-.','Color',[0 0 1]);
set(semilogy6(11),'DisplayName','C_{010}','LineStyle','-.',...
    'Color',[0 1 0]);
set(semilogy6(12),'DisplayName','C_{011}','LineStyle','-.','Color',[0 1 1]);
set(semilogy6(13),'DisplayName','C_{100}','LineStyle','-.',...
    'Color',[1 0 0]);
set(semilogy6(14),'DisplayName','C_{101}','LineStyle','-.',...
    'Color',[1 0 1]);
set(semilogy6(15),'DisplayName','C_{110}','LineStyle','-.',...
    'Color',[1 0.5 0.5]);
set(semilogy6(16),'DisplayName','C_{111}','LineStyle','-.','Color',[0 0 0]);
set(semilogy6(17),'LineWidth',2,'LineStyle','--','Color',[0 0 1]);
set(semilogy6(18),'LineWidth',2,'LineStyle','--','Color',[0 1 1]);
set(semilogy6(19),'LineWidth',3,'LineStyle','--','Color',[0 0 0]);

% Create title
title('\{1,2\}','FontSize',17.6);

% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes4,[1e-07 1000000000]);
box(axes4,'on');
% Set the remaining axes properties
set(axes4,'FontSize',16,'LineStyleOrderIndex',3,'XMinorTick','on',...
    'YMinorTick','on','YScale','log','YTick',[1e-05 1 100000],'YTickLabel',...
    {'10^{-5}','10^{0}','10^{5}'});
% Create axes
axes5 = axes('Parent',figure1,...
    'Position',[0.106958762886598 0.567615089514066 0.237113402061856 0.168262653898769]);
hold(axes5,'on');

% Create multiple lines using matrix input to semilogy
semilogy7 = semilogy(X1,YMatrix1,'Parent',axes5,'LineWidth',2,...
    'Color',[0 0 0]);
set(semilogy7(1),'DisplayName','Lysogens');
set(semilogy7(2),'DisplayName','CRISPR Bacteria','LineStyle','-.');
set(semilogy7(3),'DisplayName','Bacteriophage','LineStyle','--');

% Create multiple lines using matrix input to semilogy
semilogy8 = semilogy(X5,YMatrix5,'Parent',axes5,'LineWidth',2);
set(semilogy8(1),'DisplayName','L_{000}','Color',[0.5 0.5 0.5]);
set(semilogy8(2),'DisplayName','L_{001}','Color',[0 0 1]);
set(semilogy8(3),'DisplayName','L_{010}',...
    'Color',[0 1 0]);
set(semilogy8(4),'DisplayName','L_{011}','Color',[0 1 1]);
set(semilogy8(5),'DisplayName','L_{100}',...
    'Color',[1 0 0]);
set(semilogy8(6),'DisplayName','L_{101}',...
    'Color',[1 0 1]);
set(semilogy8(7),'DisplayName','L_{110}',...
    'Color',[1 0.5 0.5]);
set(semilogy8(8),'DisplayName','L_{111}','Color',[0 0 0]);
set(semilogy8(9),'DisplayName','C_{000}','LineStyle','-.','Color',[0.5 0.5 0.5]);
set(semilogy8(10),'DisplayName','C_{001}','LineStyle','-.','Color',[0 0 1]);
set(semilogy8(11),'DisplayName','C_{010}','LineStyle','-.',...
    'Color',[0 1 0]);
set(semilogy8(12),'DisplayName','C_{011}','LineStyle','-.','Color',[0 1 1]);
set(semilogy8(13),'DisplayName','C_{100}','LineStyle','-.',...
    'Color',[1 0 0]);
set(semilogy8(14),'DisplayName','C_{101}','LineStyle','-.',...
    'Color',[1 0 1]);
set(semilogy8(15),'DisplayName','C_{110}','LineStyle','-.',...
    'Color',[1 0.5 0.5]);
set(semilogy8(16),'DisplayName','C_{111}','LineStyle','-.','Color',[0 0 0]);
set(semilogy8(17),'LineWidth',2,'LineStyle','--','Color',[0 0 1]);
set(semilogy8(18),'LineWidth',2,'LineStyle','--','Color',[0 1 1]);
set(semilogy8(19),'LineWidth',2,'LineStyle','--','Color',[0 0 0]);

% Create title
title('\{1,1,1\}','FontSize',17.6);

% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes5,[1e-07 1000000000]);
box(axes5,'on');
% Set the remaining axes properties
set(axes5,'FontSize',16,'LineStyleOrderIndex',3,'XMinorTick','on',...
    'YMinorTick','on','YScale','log','YTick',[1e-05 1 100000],'YTickLabel',...
    {'10^{-5}','10^{0}','10^{5}'});
% Create axes
axes6 = axes('Parent',figure1,...
    'Position',[0.413659793814433 0.568983078570154 0.235709070140686 0.166966502260887]);
hold(axes6,'on');

% Create multiple lines using matrix input to semilogy
semilogy9 = semilogy(X1,YMatrix1,'Parent',axes6,'LineWidth',2,...
    'Color',[0 0 0]);
set(semilogy9(1),'DisplayName','Lysogens');
set(semilogy9(2),'DisplayName','CRISPR Bacteria','LineStyle','-.');
set(semilogy9(3),'DisplayName','Bacteriophage','LineStyle','--');

% Create multiple lines using matrix input to semilogy
semilogy10 = semilogy(X6,YMatrix6,'Parent',axes6,'LineWidth',2);
set(semilogy10(1),'DisplayName','L_{000}','Color',[0.5 0.5 0.5]);
set(semilogy10(2),'DisplayName','L_{001}','Color',[0 0 1]);
set(semilogy10(3),'DisplayName','L_{010}',...
    'Color',[0 1 0]);
set(semilogy10(4),'DisplayName','L_{011}','Color',[0 1 1]);
set(semilogy10(5),'DisplayName','L_{100}',...
    'Color',[1 0 0]);
set(semilogy10(6),'DisplayName','L_{101}',...
    'Color',[1 0 1]);
set(semilogy10(7),'DisplayName','L_{110}',...
    'Color',[1 0.5 0.5]);
set(semilogy10(8),'DisplayName','L_{111}','Color',[0 0 0]);
set(semilogy10(9),'DisplayName','C_{000}','LineStyle','-.','Color',[0.5 0.5 0.5]);
set(semilogy10(10),'DisplayName','C_{001}','LineStyle','-.','Color',[0 0 1]);
set(semilogy10(11),'DisplayName','C_{010}','LineStyle','-.',...
    'Color',[0 1 0]);
set(semilogy10(12),'DisplayName','C_{011}','LineStyle','-.','Color',[0 1 1]);
set(semilogy10(13),'DisplayName','C_{100}','LineStyle','-.',...
    'Color',[1 0 0]);
set(semilogy10(14),'DisplayName','C_{101}','LineStyle','-.',...
    'Color',[1 0 1]);
set(semilogy10(15),'DisplayName','C_{110}','LineStyle','-.',...
    'Color',[1 0.5 0.5]);
set(semilogy10(16),'DisplayName','C_{111}','LineStyle','-.','Color',[0 0 0]);
set(semilogy10(17),'LineWidth',2,'LineStyle','--','Color',[0 0 1]);
set(semilogy10(18),'LineWidth',2,'LineStyle','--','Color',[0 1 1]);
set(semilogy10(19),'LineWidth',2,'LineStyle','--','Color',[0 0 0]);

% Create title
title('\{1,1,1\}','FontSize',17.6);

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes6,[0 180]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes6,[1e-07 1000000000]);
box(axes6,'on');
% Set the remaining axes properties
set(axes6,'FontSize',16,'LineStyleOrderIndex',3,'XMinorTick','on',...
    'YMinorTick','on','YScale','log','YTick',[1e-05 1 100000],'YTickLabel',...
    {'10^{-5}','10^{0}','10^{5}'});
% Create axes
axes7 = axes('Parent',figure1,...
    'Position',[0.722905611544078 0.568983078570154 0.232819074333801 0.16707103844583]);
hold(axes7,'on');

% Create multiple lines using matrix input to semilogy
semilogy11 = semilogy(X1,YMatrix1,'Parent',axes7,'LineWidth',2,...
    'Color',[0 0 0]);
set(semilogy11(1),'DisplayName','Lysogens');
set(semilogy11(2),'DisplayName','CRISPR Bacteria','LineStyle','-.');
set(semilogy11(3),'DisplayName','Bacteriophage','LineStyle','--');

% Create multiple lines using matrix input to semilogy
semilogy12 = semilogy(X7,YMatrix7,'Parent',axes7,'LineWidth',2);
set(semilogy12(1),'DisplayName','L_{000}','Color',[0.5 0.5 0.5]);
set(semilogy12(2),'DisplayName','L_{001}','Color',[0 0 1]);
set(semilogy12(3),'DisplayName','L_{010}',...
    'Color',[0 1 0]);
set(semilogy12(4),'DisplayName','L_{011}','Color',[0 1 1]);
set(semilogy12(5),'DisplayName','L_{100}',...
    'Color',[1 0 0]);
set(semilogy12(6),'DisplayName','L_{101}',...
    'Color',[1 0 1]);
set(semilogy12(7),'DisplayName','L_{110}',...
    'Color',[1 0.5 0.5]);
set(semilogy12(8),'DisplayName','L_{111}','Color',[0 0 0]);
set(semilogy12(9),'DisplayName','C_{000}','LineStyle','-.','Color',[0.5 0.5 0.5]);
set(semilogy12(10),'DisplayName','C_{001}','LineStyle','-.','Color',[0 0 1]);
set(semilogy12(11),'DisplayName','C_{010}','LineStyle','-.',...
    'Color',[0 1 0]);
set(semilogy12(12),'DisplayName','C_{011}','LineStyle','-.','Color',[0 1 1]);
set(semilogy12(13),'DisplayName','C_{100}','LineStyle','-.',...
    'Color',[1 0 0]);
set(semilogy12(14),'DisplayName','C_{101}','LineStyle','-.',...
    'Color',[1 0 1]);
set(semilogy12(15),'DisplayName','C_{110}','LineStyle','-.',...
    'Color',[1 0.5 0.5]);
set(semilogy12(16),'DisplayName','C_{111}','LineStyle','-.','Color',[0 0 0]);
set(semilogy12(17),'LineWidth',2,'LineStyle','--','Color',[0 0 1]);
set(semilogy12(18),'LineWidth',2,'LineStyle','--','Color',[0 1 1]);
set(semilogy12(19),'LineWidth',2,'LineStyle','--','Color',[0 0 0]);

% Create title
title('\{1,1,1\}','FontSize',17.6);

% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes7,[1e-07 1000000000]);
box(axes7,'on');
% Set the remaining axes properties
set(axes7,'FontSize',16,'LineStyleOrderIndex',3,'XMinorTick','on',...
    'YMinorTick','on','YScale','log','YTick',[1e-05 1 100000],'YTickLabel',...
    {'10^{-5}','10^{0}','10^{5}'});
% Create axes
axes8 = axes('Parent',figure1,...
    'Position',[0.108178789621192 0.340528906203533 0.23422159887798 0.169242608837393]);
hold(axes8,'on');

% Create multiple lines using matrix input to semilogy
semilogy13 = semilogy(X1,YMatrix1,'Parent',axes8,'LineWidth',2,...
    'Color',[0 0 0]);
set(semilogy13(1),'DisplayName','Lysogens');
set(semilogy13(2),'DisplayName','CRISPR Bacteria','LineStyle','-.');
set(semilogy13(3),'DisplayName','Bacteriophage','LineStyle','--');

% Create multiple lines using matrix input to semilogy
semilogy14 = semilogy(X8,YMatrix8,'Parent',axes8,'LineWidth',2);
set(semilogy14(1),'DisplayName','L_{000}','Color',[0.5 0.5 0.5]);
set(semilogy14(2),'DisplayName','L_{001}','Color',[0 0 1]);
set(semilogy14(3),'DisplayName','L_{010}',...
    'Color',[0 1 0]);
set(semilogy14(4),'DisplayName','L_{011}','Color',[0 1 1]);
set(semilogy14(5),'DisplayName','L_{100}',...
    'Color',[1 0 0]);
set(semilogy14(6),'DisplayName','L_{101}',...
    'Color',[1 0 1]);
set(semilogy14(7),'DisplayName','L_{110}',...
    'Color',[1 0.5 0.5]);
set(semilogy14(8),'DisplayName','L_{111}','Color',[0 0 0]);
set(semilogy14(9),'DisplayName','C_{000}','LineStyle','-.','Color',[0.5 0.5 0.5]);
set(semilogy14(10),'DisplayName','C_{001}','LineStyle','-.','Color',[0 0 1]);
set(semilogy14(11),'DisplayName','C_{010}','LineStyle','-.',...
    'Color',[0 1 0]);
set(semilogy14(12),'DisplayName','C_{011}','LineStyle','-.','Color',[0 1 1]);
set(semilogy14(13),'DisplayName','C_{100}','LineStyle','-.',...
    'Color',[1 0 0]);
set(semilogy14(14),'DisplayName','C_{101}','LineStyle','-.',...
    'Color',[1 0 1]);
set(semilogy14(15),'DisplayName','C_{110}','LineStyle','-.',...
    'Color',[1 0.5 0.5]);
set(semilogy14(16),'DisplayName','C_{111}','LineStyle','-.','Color',[0 0 0]);
set(semilogy14(17),'LineWidth',3,'LineStyle','--','Color',[0 0 1]);
set(semilogy14(18),'LineWidth',2,'LineStyle','--','Color',[0 1 1]);
set(semilogy14(19),'LineWidth',2,'LineStyle','--','Color',[0 0 0]);

% Create title
title('\{2,1\}','FontSize',17.6);

% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes8,[1e-07 1000000000]);
box(axes8,'on');
% Set the remaining axes properties
set(axes8,'FontSize',16,'LineStyleOrderIndex',3,'XMinorTick','on',...
    'YMinorTick','on','YScale','log','YTick',[1e-05 1 100000],'YTickLabel',...
    {'10^{-5}','10^{0}','10^{5}'});
% Create axes
axes9 = axes('Parent',figure1,...
    'Position',[0.413616464033072 0.340528906203533 0.237113402061856 0.167984747202173]);
hold(axes9,'on');

% Create multiple lines using matrix input to semilogy
semilogy15 = semilogy(X1,YMatrix1,'Parent',axes9,'LineWidth',2,...
    'Color',[0 0 0]);
set(semilogy15(1),'DisplayName','Lysogens');
set(semilogy15(2),'DisplayName','CRISPR Bacteria','LineStyle','-.');
set(semilogy15(3),'DisplayName','Bacteriophage','LineStyle','--');

% Create multiple lines using matrix input to semilogy
semilogy16 = semilogy(X9,YMatrix9,'Parent',axes9,'LineWidth',2);
set(semilogy16(1),'DisplayName','L_{000}','Color',[0.5 0.5 0.5]);
set(semilogy16(2),'DisplayName','L_{001}','Color',[0 0 1]);
set(semilogy16(3),'DisplayName','L_{010}',...
    'Color',[0 1 0]);
set(semilogy16(4),'DisplayName','L_{011}','Color',[0 1 1]);
set(semilogy16(5),'DisplayName','L_{100}',...
    'Color',[1 0 0]);
set(semilogy16(6),'DisplayName','L_{101}',...
    'Color',[1 0 1]);
set(semilogy16(7),'DisplayName','L_{110}',...
    'Color',[1 0.5 0.5]);
set(semilogy16(8),'DisplayName','L_{111}','Color',[0 0 0]);
set(semilogy16(9),'DisplayName','C_{000}','LineStyle','-.','Color',[0.5 0.5 0.5]);
set(semilogy16(10),'DisplayName','C_{001}','LineStyle','-.','Color',[0 0 1]);
set(semilogy16(11),'DisplayName','C_{010}','LineStyle','-.',...
    'Color',[0 1 0]);
set(semilogy16(12),'DisplayName','C_{011}','LineStyle','-.','Color',[0 1 1]);
set(semilogy16(13),'DisplayName','C_{100}','LineStyle','-.',...
    'Color',[1 0 0]);
set(semilogy16(14),'DisplayName','C_{101}','LineStyle','-.',...
    'Color',[1 0 1]);
set(semilogy16(15),'DisplayName','C_{110}','LineStyle','-.',...
    'Color',[1 0.5 0.5]);
set(semilogy16(16),'DisplayName','C_{111}','LineStyle','-.','Color',[0 0 0]);
set(semilogy16(17),'LineWidth',3,'LineStyle','--','Color',[0 0 1]);
set(semilogy16(18),'LineWidth',2,'LineStyle','--','Color',[0 1 1]);
set(semilogy16(19),'LineWidth',2,'LineStyle','--','Color',[0 0 0]);

% Create title
title('\{2,1\}','FontSize',17.6);

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes9,[0 180]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes9,[1e-07 1000000000]);
box(axes9,'on');
% Set the remaining axes properties
set(axes9,'FontSize',16,'LineStyleOrderIndex',3,'XMinorTick','on',...
    'YMinorTick','on','YScale','log','YTick',[1e-05 1 100000],'YTickLabel',...
    {'10^{-5}','10^{0}','10^{5}'});
% Create axes
axes10 = axes('Parent',figure1,...
    'Position',[0.724150941556531 0.337792928091358 0.232819074333801 0.16830953822885]);
hold(axes10,'on');

% Create multiple lines using matrix input to semilogy
semilogy17 = semilogy(X1,YMatrix1,'Parent',axes10,'LineWidth',2,...
    'Color',[0 0 0]);
set(semilogy17(1),'DisplayName','Lysogens');
set(semilogy17(2),'DisplayName','CRISPR Bacteria','LineStyle','-.');
set(semilogy17(3),'DisplayName','Bacteriophage','LineStyle','--');

% Create multiple lines using matrix input to semilogy
semilogy18 = semilogy(X10,YMatrix10,'Parent',axes10,'LineWidth',2);
set(semilogy18(1),'DisplayName','L_{000}','Color',[0.5 0.5 0.5]);
set(semilogy18(2),'DisplayName','L_{001}','Color',[0 0 1]);
set(semilogy18(3),'DisplayName','L_{010}',...
    'Color',[0 1 0]);
set(semilogy18(4),'DisplayName','L_{011}','Color',[0 1 1]);
set(semilogy18(5),'DisplayName','L_{100}',...
    'Color',[1 0 0]);
set(semilogy18(6),'DisplayName','L_{101}',...
    'Color',[1 0 1]);
set(semilogy18(7),'DisplayName','L_{110}',...
    'Color',[1 0.5 0.5]);
set(semilogy18(8),'DisplayName','L_{111}','Color',[0 0 0]);
set(semilogy18(9),'DisplayName','C_{000}','LineStyle','-.','Color',[0.5 0.5 0.5]);
set(semilogy18(10),'DisplayName','C_{001}','LineStyle','-.','Color',[0 0 1]);
set(semilogy18(11),'DisplayName','C_{010}','LineStyle','-.',...
    'Color',[0 1 0]);
set(semilogy18(12),'DisplayName','C_{011}','LineStyle','-.','Color',[0 1 1]);
set(semilogy18(13),'DisplayName','C_{100}','LineStyle','-.',...
    'Color',[1 0 0]);
set(semilogy18(14),'DisplayName','C_{101}','LineStyle','-.',...
    'Color',[1 0 1]);
set(semilogy18(15),'DisplayName','C_{110}','LineStyle','-.',...
    'Color',[1 0.5 0.5]);
set(semilogy18(16),'DisplayName','C_{111}','LineStyle','-.','Color',[0 0 0]);
set(semilogy18(17),'LineWidth',3,'LineStyle','--','Color',[0 0 1]);
set(semilogy18(18),'LineWidth',2,'LineStyle','--','Color',[0 1 1]);
set(semilogy18(19),'LineWidth',2,'LineStyle','--','Color',[0 0 0]);

% Create title
title('\{2,1\}','FontSize',17.6);

% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes10,[1e-07 1000000000]);
box(axes10,'on');
% Set the remaining axes properties
set(axes10,'FontSize',16,'LineStyleOrderIndex',3,'XMinorTick','on',...
    'YMinorTick','on','YScale','log','YTick',[1e-05 1 100000],'YTickLabel',...
    {'10^{-5}','10^{0}','10^{5}'});
% Create axes
axes11 = axes('Parent',figure1,...
    'Position',[0.107595296136417 0.118217673823827 0.236115787300694 0.163892171151459]);
hold(axes11,'on');

% Create multiple lines using matrix input to semilogy
semilogy19 = semilogy(X1,YMatrix1,'Parent',axes11,'LineWidth',2,...
    'Color',[0 0 0]);
set(semilogy19(1),'DisplayName','Lysogens');
set(semilogy19(2),'DisplayName','CRISPR Bacteria','LineStyle','-.');
set(semilogy19(3),'DisplayName','Bacteriophage','LineStyle','--');

% Create multiple lines using matrix input to semilogy
semilogy20 = semilogy(X11,YMatrix11,'Parent',axes11,'LineWidth',2);
set(semilogy20(1),'DisplayName','L_{000}','Color',[0.5 0.5 0.5]);
set(semilogy20(2),'DisplayName','L_{001}','Color',[0 0 1]);
set(semilogy20(3),'DisplayName','L_{010}',...
    'Color',[0 1 0]);
set(semilogy20(4),'DisplayName','L_{011}','Color',[0 1 1]);
set(semilogy20(5),'DisplayName','L_{100}',...
    'Color',[1 0 0]);
set(semilogy20(6),'DisplayName','L_{101}',...
    'Color',[1 0 1]);
set(semilogy20(7),'DisplayName','L_{110}',...
    'Color',[1 0.5 0.5]);
set(semilogy20(8),'DisplayName','L_{111}','Color',[0 0 0]);
set(semilogy20(9),'DisplayName','C_{000}','LineStyle','-.','Color',[0.5 0.5 0.5]);
set(semilogy20(10),'DisplayName','C_{001}','LineStyle','-.','Color',[0 0 1]);
set(semilogy20(11),'DisplayName','C_{010}','LineStyle','-.',...
    'Color',[0 1 0]);
set(semilogy20(12),'DisplayName','C_{011}','LineStyle','-.','Color',[0 1 1]);
set(semilogy20(13),'DisplayName','C_{100}','LineStyle','-.',...
    'Color',[1 0 0]);
set(semilogy20(14),'DisplayName','C_{101}','LineStyle','-.',...
    'Color',[1 0 1]);
set(semilogy20(15),'DisplayName','C_{110}','LineStyle','-.',...
    'Color',[1 0.5 0.5]);
set(semilogy20(16),'DisplayName','C_{111}','LineStyle','-.','Color',[0 0 0]);
set(semilogy20(17),'LineWidth',2,'LineStyle','--','Color',[0 0 1]);
set(semilogy20(18),'LineWidth',3,'LineStyle','--','Color',[0 1 1]);
set(semilogy20(19),'LineWidth',1,'LineStyle','--','Color',[0 0 0]);

% Create title
title('\{3\}','FontSize',17.6);

% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes11,[1e-07 1000000000]);
box(axes11,'on');
% Set the remaining axes properties
set(axes11,'FontSize',16,'LineStyleOrderIndex',3,'XMinorTick','on',...
    'YMinorTick','on','YScale','log','YTick',[1e-05 1 100000],'YTickLabel',...
    {'10^{-5}','10^{0}','10^{5}'});
% Create axes
axes12 = axes('Parent',figure1,...
    'Position',[0.414563771592363 0.118217673823827 0.23562412342216 0.162529773331295]);
hold(axes12,'on');

% Create multiple lines using matrix input to semilogy
semilogy21 = semilogy(X1,YMatrix1,'Parent',axes12,'LineWidth',2,...
    'Color',[0 0 0]);
set(semilogy21(1),'DisplayName','Lysogens');
set(semilogy21(2),'DisplayName','CRISPR Bacteria','LineStyle','-.');
set(semilogy21(3),'DisplayName','Bacteriophage','LineStyle','--');

% Create multiple lines using matrix input to semilogy
semilogy22 = semilogy(X12,YMatrix12,'Parent',axes12,'LineWidth',2);
set(semilogy22(1),'DisplayName','L_{000}','Color',[0.5 0.5 0.5]);
set(semilogy22(2),'DisplayName','L_{001}','Color',[0 0 1]);
set(semilogy22(3),'DisplayName','L_{010}',...
    'Color',[0 1 0]);
set(semilogy22(4),'DisplayName','L_{011}','Color',[0 1 1]);
set(semilogy22(5),'DisplayName','L_{100}',...
    'Color',[1 0 0]);
set(semilogy22(6),'DisplayName','L_{101}',...
    'Color',[1 0 1]);
set(semilogy22(7),'DisplayName','L_{110}',...
    'Color',[1 0.5 0.5]);
set(semilogy22(8),'DisplayName','L_{111}','Color',[0 0 0]);
set(semilogy22(9),'DisplayName','C_{000}','LineStyle','-.','Color',[0.5 0.5 0.5]);
set(semilogy22(10),'DisplayName','C_{001}','LineStyle','-.','Color',[0 0 1]);
set(semilogy22(11),'DisplayName','C_{010}','LineStyle','-.',...
    'Color',[0 1 0]);
set(semilogy22(12),'DisplayName','C_{011}','LineStyle','-.','Color',[0 1 1]);
set(semilogy22(13),'DisplayName','C_{100}','LineStyle','-.',...
    'Color',[1 0 0]);
set(semilogy22(14),'DisplayName','C_{101}','LineStyle','-.',...
    'Color',[1 0 1]);
set(semilogy22(15),'DisplayName','C_{110}','LineStyle','-.',...
    'Color',[1 0.5 0.5]);
set(semilogy22(16),'DisplayName','C_{111}','LineStyle','-.','Color',[0 0 0]);
set(semilogy22(17),'LineWidth',2,'LineStyle','--','Color',[0 0 1]);
set(semilogy22(18),'LineWidth',3,'LineStyle','--','Color',[0 1 1]);
set(semilogy22(19),'LineWidth',1,'LineStyle','--','Color',[0 0 0]);

% Create title
title('\{3\}','FontSize',17.6);

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes12,[0 180]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes12,[1e-07 1000000000]);
box(axes12,'on');
% Set the remaining axes properties
set(axes12,'FontSize',16,'LineStyleOrderIndex',3,'XMinorTick','on',...
    'YMinorTick','on','YScale','log','YTick',[1e-05 1 100000],'YTickLabel',...
    {'10^{-5}','10^{0}','10^{5}'});
% Create axes
axes13 = axes('Parent',figure1,...
    'Position',[0.723724642603482 0.11684968476774 0.232819074333801 0.165260160207546]);
hold(axes13,'on');

% Create multiple lines using matrix input to semilogy
semilogy23 = semilogy(X1,YMatrix1,'Parent',axes13,'LineWidth',2,...
    'Color',[0 0 0]);
set(semilogy23(1),'DisplayName','Lysogens');
set(semilogy23(2),'DisplayName','CRISPR Bacteria','LineStyle','-.');
set(semilogy23(3),'DisplayName','Bacteriophage','LineStyle','--');

% Create multiple lines using matrix input to semilogy
semilogy24 = semilogy(X13,YMatrix13,'Parent',axes13,'LineWidth',2);
set(semilogy24(1),'DisplayName','L_{000}','Color',[0.5 0.5 0.5]);
set(semilogy24(2),'DisplayName','L_{001}','Color',[0 0 1]);
set(semilogy24(3),'DisplayName','L_{010}',...
    'Color',[0 1 0]);
set(semilogy24(4),'DisplayName','L_{011}','Color',[0 1 1]);
set(semilogy24(5),'DisplayName','L_{100}',...
    'Color',[1 0 0]);
set(semilogy24(6),'DisplayName','L_{101}',...
    'Color',[1 0 1]);
set(semilogy24(7),'DisplayName','L_{110}',...
    'Color',[1 0.5 0.5]);
set(semilogy24(8),'DisplayName','L_{111}','Color',[0 0 0]);
set(semilogy24(9),'DisplayName','C_{000}','LineStyle','-.','Color',[0.5 0.5 0.5]);
set(semilogy24(10),'DisplayName','C_{001}','LineStyle','-.','Color',[0 0 1]);
set(semilogy24(11),'DisplayName','C_{010}','LineStyle','-.',...
    'Color',[0 1 0]);
set(semilogy24(12),'DisplayName','C_{011}','LineStyle','-.','Color',[0 1 1]);
set(semilogy24(13),'DisplayName','C_{100}','LineStyle','-.',...
    'Color',[1 0 0]);
set(semilogy24(14),'DisplayName','C_{101}','LineStyle','-.',...
    'Color',[1 0 1]);
set(semilogy24(15),'DisplayName','C_{110}','LineStyle','-.',...
    'Color',[1 0.5 0.5]);
set(semilogy24(16),'DisplayName','C_{111}','LineStyle','-.','Color',[0 0 0]);
set(semilogy24(17),'LineWidth',2,'LineStyle','--','Color',[0 0 1]);
set(semilogy24(18),'LineWidth',3,'LineStyle','--','Color',[0 1 1]);
set(semilogy24(19),'LineWidth',1,'LineStyle','--','Color',[0 0 0]);

% Create title
title('\{3\}','FontSize',17.6);

% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes13,[1e-07 1000000000]);
box(axes13,'on');
% Set the remaining axes properties
set(axes13,'FontSize',16,'LineStyleOrderIndex',3,'XMinorTick','on',...
    'YMinorTick','on','YScale','log','YTick',[1e-05 1 100000],'YTickLabel',...
    {'10^{-5}','10^{0}','10^{5}'});
